name: Run tests and export schema

on:
  workflow_call:
    outputs:
      schema:
        description: "Name of the schema file from the artifact"
        value: ${{ jobs.test.outputs.schema }}
      schema_artifact:
        description: "Name of the artifact to download to get the schema"
        value: ${{ jobs.test.outputs.schema_artifact }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test on Python 3.10
    env:
      SCHEMA_FILE: __rover_schema.graphql
      SCHEMA_ARTIFACT: schema
    outputs:
      schema: ${{ env.SCHEMA_FILE }}
      schema_artifact: ${{ env.SCHEMA_ARTIFACT }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --statistics
      - name: Test with pytest
        run: |
          pytest tests/
      - name: Export schema
        run: |
          strawberry export-schema api.schema > ${{ env.SCHEMA_FILE }}
      - name: Upload schema to artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.SCHEMA_FILE }}
          name: ${{ env.SCHEMA_ARTIFACT }}
